// Sample courses data for testing and development
const sampleCourses = [
  {
    title: 'React.js Complete Course',
    description: 'Master React.js from basics to advanced concepts including hooks, context API, and Redux. Build real-world projects and learn best practices.',
    instructor: 'John Smith',
    duration: '8 weeks',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
    status: 'published',
    category: 'Web Development',
    level: 'intermediate',
    rating: 4.7,
    enrolledCount: 250,
  },
  {
    title: 'Node.js Backend Development',
    description: 'Learn to build scalable backend applications with Node.js, Express, MongoDB, and implement RESTful APIs with authentication.',
    instructor: 'Sarah Johnson',
    duration: '6 weeks',
    price: 3999,
    image: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800',
    status: 'published',
    category: 'Backend Development',
    level: 'intermediate',
    rating: 4.5,
    enrolledCount: 180,
  },
  {
    title: 'Python for Data Science',
    description: 'Complete Python course covering NumPy, Pandas, Matplotlib, and machine learning basics. Perfect for aspiring data scientists.',
    instructor: 'Dr. Emily Chen',
    duration: '10 weeks',
    price: 5999,
    image: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800',
    status: 'published',
    category: 'Data Science',
    level: 'beginner',
    rating: 4.8,
    enrolledCount: 320,
  },
  {
    title: 'Mobile App Development with React Native',
    description: 'Build cross-platform mobile applications for iOS and Android using React Native. Learn navigation, state management, and API integration.',
    instructor: 'Michael Brown',
    duration: '7 weeks',
    price: 4499,
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
    status: 'published',
    category: 'Mobile Development',
    level: 'intermediate',
    rating: 4.6,
    enrolledCount: 150,
  },
  {
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the principles of user interface and user experience design. Master Figma, design systems, and create stunning user interfaces.',
    instructor: 'Jessica Martinez',
    duration: '5 weeks',
    price: 3499,
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    status: 'published',
    category: 'Design',
    level: 'beginner',
    rating: 4.9,
    enrolledCount: 280,
  },
  {
    title: 'Advanced JavaScript ES6+',
    description: 'Deep dive into modern JavaScript including async/await, promises, modules, and advanced programming patterns.',
    instructor: 'David Wilson',
    duration: '4 weeks',
    price: 2999,
    image: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800',
    status: 'draft',
    category: 'Web Development',
    level: 'advanced',
    rating: 0,
    enrolledCount: 0,
  },
];

module.exports = sampleCourses;

